using System.IO;
using UnityEditor;
using UnityEngine;

namespace LurkingNinja.Localization.Editor
{
    public class LocalizationCodegenSettings : ScriptableObject
    {
        private const string LocalizationCodegenConfigFolder = "Assets/Plugins/LurkingNinja/Editor";
        private const string LocalizationCodegenConfigFile =
            LocalizationCodegenConfigFolder + "/LocalizationCodegenConfig.asset";

        public bool isEnabled = true;

        public string nameSpace = "LurkingNinja.Localization";
        public string path = "Assets/Plugins/LurkingNinja/LocalizationCodegen/";
        [Space(10), TextArea(20, 20)]
        public string template = @"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated: {0}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using UnityEngine.Localization.Settings;

{1}
{{
    public static partial class I18N
    {{
        public static class {2}
        {{
            private const string @NAME = ""{3}""; 
{4}
        }}
    }}
}}";

        private static LocalizationCodegenSettings _config;

        public static LocalizationCodegenSettings Get => GenerateConfigFile();
        
        private static LocalizationCodegenSettings GenerateConfigFile()
        {
            if (_config != null) return _config;
            _config = AssetDatabase.LoadAssetAtPath<LocalizationCodegenSettings>(LocalizationCodegenConfigFile);
            if (_config != null) return _config;
            if (!Directory.Exists(LocalizationCodegenConfigFolder))
                Directory.CreateDirectory(LocalizationCodegenConfigFolder);
            _config = CreateInstance<LocalizationCodegenSettings>();
            AssetDatabase.CreateAsset(_config, LocalizationCodegenConfigFile);
            AssetDatabase.SaveAssets();
            return _config;
        }
        
        [MenuItem("Tools/LurkingNinja/Localization Codegen Config", false)]
        private static void InputCodegenConfig()
        {
            GenerateConfigFile();
            EditorUtility.FocusProjectWindow();
            EditorGUIUtility.PingObject(_config);
            Selection.activeObject = _config;
        }
    }
}
